# -*- coding: utf-8 -*-
"""Homework4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IcBHPs2uiyhlWcTUy5iEKYLQLojrnFbg
"""

import random

def randQuicksort(arr, low = 0, high = None):

  if high is None:
    high = len(arr) - 1

  if low < high:

    #Randomized Pivot
    pivot = random.randint(low, high)
    arr[high], arr[pivot] = arr[pivot], arr[high]

    i = low - 1
    for j in range(low, high):

      if arr[j] <= arr[high]:
        i += 1
        arr[i], arr[j] = arr[j], arr[i]

    arr[i + 1], arr[high] = arr[high], arr[i + 1]

    randQuicksort(arr, low, i)
    randQuicksort(arr, i + 2, high)

arr = [5, 8, 2, 0, 4, 10]
randQuicksort(arr)
print(arr)

def heapsort(arr):

  def heapify(n, i):
    largest = i
    l = 2 * i + 1
    r = 2 * i + 2

    if l < n and arr[l] > arr[largest]:
      largest = l

    if r < n and arr[r] > arr[largest]:
      largest = r

    if largest != i:
      arr[i], arr[largest] = arr[largest], arr[i]
      heapify(n, largest)

  n = len(arr)

  for i in range(n // 2 - 1, -1, -1):
    heapify(n, i)

  for i in range(n - 1, 0, -1):
    arr[i], arr[0] = arr[0], arr[i]
    heapify(i, 0)

arr = [5, 8, 2, 0, 4, 10]
heapsort(arr)
print(arr)