# -*- coding: utf-8 -*-
"""Homework4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IcBHPs2uiyhlWcTUy5iEKYLQLojrnFbg
"""

import random
import tracemalloc
import time
import sys

def randQuicksort(arr, low = 0, high = None):

  if high is None:
    high = len(arr) - 1

  if low < high:

    #Randomized Pivot
    pivot = random.randint(low, high)
    arr[high], arr[pivot] = arr[pivot], arr[high]

    i = low - 1
    for j in range(low, high):

      if arr[j] <= arr[high]:
        i += 1
        arr[i], arr[j] = arr[j], arr[i]

    arr[i + 1], arr[high] = arr[high], arr[i + 1]

    randQuicksort(arr, low, i)
    randQuicksort(arr, i + 2, high)


def heapsort(arr):

  def heapify(n, i):
    largest = i
    l = 2 * i + 1
    r = 2 * i + 2

    if l < n and arr[l] > arr[largest]:
      largest = l

    if r < n and arr[r] > arr[largest]:
      largest = r

    if largest != i:
      arr[i], arr[largest] = arr[largest], arr[i]
      heapify(n, largest)

  n = len(arr)

  for i in range(n // 2 - 1, -1, -1):
    heapify(n, i)

  for i in range(n - 1, 0, -1):
    arr[i], arr[0] = arr[0], arr[i]
    heapify(i, 0)


def analysis():

  sizes = [10**3, 10**4, 10**5]
  algos = {"Quicksort" : randQuicksort, "Heapsort" : heapsort}

  print(f"{'Algorithm':<10} | {'N':<7} | {'Test Case':<15} | {'Run Time':<14} | {'Memory Used':<16} | {'Status'}")
  print("-" * 100)

  for n in sizes:
    base_arr = [random.uniform(0.0, 1000.0) for _ in range(n)]
    test_cases = {
      "Random Order": base_arr.copy(),
      "Repeated Values": [random.choice([1.5, 42.0, 7.33, 99.9]) for _ in range(n)],
      "Already Sorted": sorted(base_arr),
      "Reverse Sorted": sorted(base_arr, reverse=True)
    }

    for case_name, data in test_cases.items():
            for algo_name, algo_func in algos.items():

              # New data for every algotrithm
              test_arr = data.copy()
              tracemalloc.start()
              start_time = time.perf_counter()

              status = "Success"
              end_time = 0.0

              try:
                  algo_func(test_arr)
                  end_time = time.perf_counter() - start_time

              except RecursionError:
                status = "Recursion Error"

              current, peak = tracemalloc.get_traced_memory()
              memory_mb = peak / (1024 * 1024)
              tracemalloc.stop()

              if status == "Success":
                    time_str = f"{end_time:.4f}s"
                    mem_str = f"{memory_mb:.4f}MB"

              else:
                  time_str = "N/A"
                  mem_str = "N/A"

              print(f"{algo_name} | N={n} | {case_name} | Time: {time_str} | Mem: {mem_str} | {status}")



analysis()

#No AI was used in this homework